### ISSUE TITLE
ECONNRESET error

### ISSUE THREAD

**Issue by imatarasso** [schemers/homebridge-hunterdouglas-platinum#12]
Hello - I see this error regularly on my HomeBridge terminal log (running Homebridge on Docker via Synology)

refreshIfNeeded Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
    errno: -104,
    code: 'ECONNRESET',
    syscall: 'read'
}

Any idea what might be causing this?  Thank you in advance for your assistance.

**Comment by schemers** [comment]
I think it is related to the platinum bridge. By default the plugin polls the status of the blinds every 60 seconds (in case they were changed with a remote). I think occasionally the bridge just runs into an issue and closes the connection so nodejs returns that error.
