### ISSUE TITLE
Back-to-back commands cause erratic behavior

### ISSUE THREAD

**Issue by lukebrannon1** [schemers/homebridge-hunterdouglas-platinum#3]
Hi there,

Really enjoying this plugin and appreciate your work to stabilize it over the last few releases! 

When creating scenes that result in multiple commands to set shade positions, they often don't yield expected results. I have found in most cases that sending more than 1 shade position command at a time seems to freak out the Platinum Gateway.

Might I make a suggestion? In some of my previous scripts I wrote to control these shades, I implemented a queue to process the commands to the Platinum Gateway and rate-limit the shade position commands that could be sent to the gateway to only 1 command every (approx) 5 seconds. This excluded commands used to check status ($dat, etc). Note this didn't delay the first command sent by 5 seconds, but only delayed subsequent shade position commands so that only 1 was sent in a 5 second window.

What are your thoughts about making a rate-limit duration a configurable item in this plugin's configuration? Like I mentioned, 1 shade position change within a 5 second window seemed to work best in the past when executing scenes that spanned multiple rooms.

**Comment by schemers** [comment]
Thanks. I did put in a delay (`setPositionDelayMsecs`) when setting a single blind (or the virtual room blind), but haven't tried using scenes, which would definitely bypass that logic.

I currently have some logic that attempts to refresh values after setting a new position, could potentially be causing a race condition caused when using scenes. Might be worth trying to change that logic to not explicitly refresh. 

Your suggesting is good one though, as even with removing that logic I could see how firing off a bunch of sets in rapid succession could cause issues. I also currently just create a new connection on each set so as to not worry about dealing with stale connections, etc, which probably exacerbates the problem.

I'll try and poke around with it in between work breaks.

**Comment by lukebrannon1** [comment]
Thanks for considering @schemers! HD makes so many different types of products and users have them setup in so many different configurations that I can appreciate the difficulty in trying to capture all those cases in this plugin. I think some of the stuff we're talking about could definitely be beneficial if configurable in the config.json. That might help me debug as well. I'd offer to poke through the code to see if I could contribute, but unfortunately I'm not that well-versed with nodejs. Would definitely help in any way I'm able, even if just debugging and bouncing ideas around.

**Comment by schemers** [comment]
I did some testing by creating a scene that sets four shades to 90%, 80%, 70%, 60%, and it failed immediately.

I added throttling in between sending set commands (5 secs), and it consistently worked.

I released 1.3.0 with the new `setPositionThrottleRateMsecs` option that defaults to 5000 msecs. 

please let me know if it works

**Comment by schemers** [comment]
btw, as I was implementing, I realized what I can should probably do instead is combine `setPositionDelayMsecs` and `setPositionThrottleRateMsecs` into a single option that basically batches up all blind changes (`setPositionDelayMsecs` is basically doing that for a single blind-id), and then when the delay expires, make a single connection and then do all the sets at once (this is basically how the virtual blind works, it is setting all the blinds in a room at the same time within a transaction).

this would get all the blind moving a lot quicker without the 5s pause between each blind.

I'll probably work on optimizing at some point

**Comment by lukebrannon1** [comment]
After installing 1.3.0 it's working great. Scenes are consistently behaving. 

I think where things are now is actually perfect. If only firing a single command it fires very quickly (whatever delay is set in `setPositionDelayMsecs`) and if firing a bunch of commands they are throttled by `setPositionThrottleRateMsecs`. To me, that's the best combo rather than having a single throttle/delay. I feel like a single setting might unnecessarily delay commands from being sent in cases where only 1 command needs to be sent (instead of several in a scene).

GREAT work!

**Comment by schemers** [comment]
glad to hear. I did try to optimize things by batching up multiple sets and attempting to do them one after the other (on the same connection) and found it to be very erratic unless the position of all shades being set was exactly the same, which explains why the virtual room shade is working fine but anything else requires a delay. 

I'm going to play around with it a little more this weekend, but will most likely leave the behavior as-is since it does appear to be very stable, and I agree that both settings make sense.

**Comment by lukebrannon1** [comment]
That sounds consistent with what I've seen in the past. 

One thing to note - a couple of my scenes include setting virtual room shades for multiple rooms at the same time. That is also now working perfectly with a 5 second delay between each room, so the throttle is not only beneficial for individual shades, but also for the virtual room shades.
